server:
  port: 8088
  servlet:
    context-path: /log
    tomcat:
      uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
  # 配置文件
  profiles:
    active: test
  # eureka 注册名称
  application:
    name: rain-log
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rao.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# 通用 mapper
mapper:
  mappers: com.rao.mapper.RainBaseDao
  identity: MYSQL

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# dao 的日志
logging:
  level:
    com:
      rao:
        dao: debug

# 开启断路器
feign:
  hystrix:
    enabled: true

