server:
  port: 8084
  servlet:
    context-path: /resource
    tomcat:
      uri-encoding: utf-8
      
spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true

  # eureka 注册名称
  application:
    name: rain-resource
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # 数据源  
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain_resource_dev

  # redis
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 0  

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rao.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# 通用 mapper
mapper:
  mappers: com.rao.mapper.RainBaseDao
  identity: MYSQL

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# dao 的日志        
logging:
  level:
    com:
      rao:
        dao: debug

# eureka    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/    

# security
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8086/auth/oauth/token
      user-authorization-uri: http://localhost:8086/auth/oauth/authorize
      grant-type: password,refresh_token
      scope: backend
    resource:
      user-info-uri: http://localhost:8086/auth/user/info

# 本地 oss 配置
local-oss:
  wd-url: http://127.0.0.1:8082/storage/storage
  lm-url: http://127.0.0.1:8082/storage/storage
  wd-rest-api: http://127.0.0.1:8082/storage/resource/storage/file_upload.html
  lm-rest-api: http://127.0.0.1:8082/storage/resource/storage/file_upload.html
  local-oss: true
