server:
  port: 8086
  servlet:
    context-path: /auth
    tomcat:
      uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
  # 配置文件
  profiles:
    active: dev
  # eureka 注册名称
  application:
    name: rain-auth
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rao.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# dao 的日志        
logging:
  level:
    com:
      rao:
        dao: debug
