server:
  port: 8086
  servlet:
    context-path: /auth
    tomcat:
      uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
      
  # eureka 注册名称
  application:
    name: rain-auth
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # 数据源  
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/rain_auth_dev  
      
# eureka    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      
feign:
  hystrix:
    enabled: true