# 注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}