server:
  port: 8085
  servlet:
    context-path: /user
    tomcat:
      uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true

  # eureka 注册名称
  application:
    name: rain-user
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # 数据源
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rain_user_dev

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rao.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# dao 的日志        
logging:
  level:
    com:
      rao:
        dao: debug

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



